name: PR merge
on:
  push:
jobs:
  gather_diffs:
    runs-on: ubuntu-latest
    outputs:
      all: ${{ steps.shared.outputs.matches }}
      service_a: ${{ steps.service_a.outputs.matches }}
      service_b: ${{ steps.service_b.outputs.matches }}
      service_c: ${{ steps.service_c.outputs.matches }}
      service_d: ${{ steps.service_d.outputs.matches }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
#       - name: Check Shared
#         id: shared
#         run: |
#           echo "::set-output name=matches::false"
#       - name: Check service_a
#         id: service_a
#         run: |
#           echo "::set-output name=matches::false" 
      - name: Check service_b
        id: service_b
        run: |
          echo "::set-output name=matches::true"
      - name: Check service_c
        id: service_c
        run: |
          echo "::set-output name=matches::false"

  service_a:
    runs-on: ubuntu-latest
    needs: gather_diffs
    if: " needs.gather_diffs.outputs.all  || needs.gather_diffs.outputs.service_a  " 
    steps:
     - run: echo "service_a will deploy"
  service_b:
    needs: [gather_diffs, service_a]
    runs-on: ubuntu-latest
    if: always() && ( needs.gather_diffs.outputs.all  || needs.gather_diffs.outputs.service_a )
    steps:
     - run: echo "service_b will deploy"
