name: PR merge
on:
  chceck_suite:
  #pull_request:
   # types: [opened,ready_for_review,edited]
    #branches:
     # - master
jobs:
 merge:
    name: Merge pull request
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Merge
        uses: actions/github-script@0.8.0
        with:
          script: |
            await github.pulls.merge({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number
            })
          github-token: "${{ secrets.PackagePAT }}"
