name: test bash
on: push

jobs:
  run-package-macos:	
   name: test
   runs-on: macOS-latest	

   steps:	    
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python 2.7	
      uses: actions/setup-python@v1	
      with:
        python-version: 2.7
    - run: |
        brew update
        brew install zlib
        brew info zlib 
