name: node ci 1205

on: 
  push:
    paths: 
     - 'dev.txt'
     - '.github/workflows/npm.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: 'https://registry.npmjs.org'

    #- uses: webfactory/ssh-agent@v0.2.0
    #  with:
    #    ssh-private-key: ${{ secrets.private_ssh }}

    - name: Install dependencies
      run: yarn install
      
 
    
# `npm rebuild` will run all those post-install scripts for us.

#    - run: npm rebuild && npm run prepare --if-present
  two:
     needs: [build]
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v1   
     - uses: actions/setup-node@v1
       with:
         node-version: 12
         registry-url: 'https://registry.npmjs.org'
     - uses: actions/cache@v1
       id: restore-cache
       with:
         path: ~/.npm
         key:  ${{ runner.os }}-node-${{ hashFiles('dev.txt') }}
         restore-keys: |
            ${{ runner.os }}-node-
     - name : "install npm"
       if: steps.restore-cache.outputs.cache-hit != 'true'
       run: |
          cat /home/runner/work/_temp/.npmrc
          npm install
       env:
         NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

     
