name: node ci 1205

on: 
  push:
    paths: 
     - 'dev.txt'
     - '.github/workflows/npm.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12

    - uses: webfactory/ssh-agent@v0.2.0
      with:
        ssh-private-key: ${{ secrets.private_ssh }}

    - name: Install dependencies
      run: npm install
      
 

     
