name: trigger by another workflow

on:
  pull_request:
    types: [edited]

env:
  NODE_VERSION: 12.x

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: | 
          echo "$GITHUB_CONTEXT"
          commits=${{ join(github.event.pull_request.labels.*.name, ', ') }}
          echo $commits
  
