name: trigger by another workflow

on:
  pull_request:


env:
  NODE_VERSION: 12.x

jobs:
  deploy:
    name: merge
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: git command
        run: | 
          git merge-base --fork-point master
