name: trigger by another workflow

on:
  push:


env:
  NODE_VERSION: 12.x

jobs:
  deploy:
    name: merge
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v1
      - name: git command
        run: | 
           git checkout origin/dev    
           git merge-base --fork-point origin/master
           
